n = input("Escreva alguma coisa: ")
print('É numérico? ', n.isnumeric())
print('É alfabetico? ', n.isalpha())
print('É alfanumérico? ', n.isalnum())
print('É decimal? ', n.isdecimal())
print('É identificador? ', n.isidentifier())
print('É minuscula? ', n.islower())
print('É maiúscula? ', n.isupper())
print('É espaços? ', n.isspace())
print('É título? ', n.istitle())
print('É imprimível? ', n.isprintable())